name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install Dependencies
        working-directory: agrinext
        run: flutter pub get

      - name: Build and Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: agrinext
          baseHref: /AgriNext/   # 👈 Must match your **repo** name exactly (case-sensitive)
